### ISSUE TITLE
how to reconnect in case deluge daemon restarts

### ISSUE THREAD

**Issue by engrbm87** [JohnDoee/deluge-client#15]
Hello,
I am using Home Assistant to monitor Deluge using the deluge_client. In case the deluge daemon stops for any reason i am not able to re-connect to the daemon once it is back online.
If i try to call the `connect()` function i get a `ValueError: attempt to connect already-connected SSLSocket!
`
I tried to call the `disconnect()` before calling `connect()` again but i get the same above error.
Any suggestions on how to properly reconnect to deluge daemon.

**Comment by JohnDoee** [comment]
I generally use the client for one-off operations and create a new instance every time.

If you want to re-use the client instance then try

    client.disconnect()
    client._create_socket()
    client.connected = False
    client.connect()

IF this works for you, please tell me here and I'll try to work that into the client.

How do you detect that connection has been lost and did you have auto-reconnect in mind ?

**Comment by JohnDoee** [comment]
Can you try the new version I've commited?

You can install it with
`pip install git+https://github.com/JohnDoee/deluge-client.git#develop`
and there is an example on how to use reconnect [in the new README file here](https://github.com/JohnDoee/deluge-client#usage)

**Comment by engrbm87** [comment]
👍 Thanks a lot for the new reconnect option. This solved my problem without having to change anything in the code from my side. I just run the call function and in case the connection was lost before it simply reconnects.
