### ISSUE TITLE
`core.resume_all_torrents` and `core.pause_all_torrents` are not working properly

### ISSUE THREAD

**Issue by engrbm87** [JohnDoee/deluge-client#16]
I would appreciate your help in testing these calls. here is my problem:
I have deluge daemon and deluge-web version 1.3.13 installed
1. Add a couple of torrents to test
2. Using deluge_client call `core.pause_all_torrents`
3. Check the torrents in deluge-web and find that they are paused
4. try to resume a torrent from deluge-web, it will be stuck as "paused" and doesn't resume until i restart deluge daemon.

If I replace the above call with `core.pause_torrent` and specify the torrent id it works fine and I can resume it later from deluge-web or by calling `core.resume_torrent`.

**Comment by JohnDoee** [comment]
I don't know these things off-hand, you need to dig around in Deluge source code to learn the inner workings of commands.

**Comment by gazpachoking** [comment]
`pause_all_torrents` pauses the whole libtorrent session (and then you have to resume the session for _any_ torrents to continue running.) If you want a regular pause on all torrents, you should probably loop through all the torrents pausing them individually.
