### ISSUE TITLE
Exceptions on python 3 with decode_utf8=True

### ISSUE THREAD

**Issue by gazpachoking** [JohnDoee/deluge-client#20]
Seems if the client is set to decode utf8 already, we have a problem creating an exception returned from deluge:
```
Traceback (most recent call last):
  File "C:/Users/Chase/PycharmProjects/deluge-client/test.py", line 7, in <module>
    print(a.call('core.get_free_space', '2', '3'))
  File "C:\Users\Chase\PycharmProjects\deluge-client\deluge_client\client.py", line 197, in call
    return self._receive_response(self.deluge_version)
  File "C:\Users\Chase\PycharmProjects\deluge-client\deluge_client\client.py", line 173, in _receive_response
    exception = type(str(exception_type.decode('utf-8', 'ignore')), (Exception, ), {})
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by gazpachoking** [comment]
I guess my first question before working on a fix is: Do we need to make decode_utf8 be optional? My feeling is that text should be text, on both python 2 and 3 automatically. (i.e. py2 unicode, py3 str)

**Comment by JohnDoee** [comment]
Although it's not the biggest of libraries, I want to do proper deprecation.

The only way I could find without breaking stuff on a release is to do it in two stages

* First make users to set decode_utf8=True
* Second make users to remove it completely

What do you think about that ?
