### ISSUE TITLE
pytest?

### ISSUE THREAD

**Issue by gazpachoking** [JohnDoee/deluge-client#23]
How do you feel about pytest? I was thinking about adding some more tests, to address #20, potentially more, and I like the pytest format quite a bit better than nose. How do you feel on the matter? I can stick with nose if you prefer.

**Comment by JohnDoee** [comment]
I have no strong feelings about pytest and since you already made it we'll go with it.

If you fix up #21 and #22 to match this, I'll merge all three and get the Appveyor test working.
