### ISSUE TITLE
Plaintext passwords shown in log

### ISSUE THREAD

**Issue by scstraus** [JohnDoee/deluge-client#30]
Currently the client shows plaintext passwords in the log as shown:
```
Calling reqid 4 method 'daemon.login' with args:('USERNAME', 'PASSWORD') kwargs:{}
```
Could this be removed or at least made optional?

**Comment by JohnDoee** [comment]
Sure!

Keep in mind that the password is also in clear-text in the auth file.

**Comment by scstraus** [comment]
Thanks! I use it within Home Assistant. My auth keys I keep in a secrets file which I don't have to share. But sometimes people ask for logs for debugging, and it's nice to not have to search them top to bottom for passwords.

**Comment by JohnDoee** [comment]
That's fair

I wonder if it'd be smart to filter other stuff out too or just straight up remove command arguments.

Anyways, the password is gone with 1.7.1, thanks for reporting it!

**Comment by scstraus** [comment]
Wow thanks for the quick fix! For me, removal of password is enough.
