### ISSUE TITLE
python 3.8 compatibility

### ISSUE THREAD

**Issue by cimbi01** [JohnDoee/deluge-client#39]
Not compatible with python 3.8, only python 3.7

**Comment by bozhodimitrov** [comment]
@cimbi01 What do you mean by not compatible?
I just tested the client with Python 3.8.1 and it still works (sends calls and retrieves data).

**Comment by JohnDoee** [comment]
It's probably in the classifiers, it should not matter though. The package on pypi is matching all python versions to begin with.

**Comment by cimbi01** [comment]
Sorry, yes it does work, i just had some coding issues :)
