### ISSUE TITLE
Deluge v2.0b2.dev daemon.login timeout ... ?

### ISSUE THREAD

**Issue by kslr** [JohnDoee/deluge-client#6]
```
>>> client = DelugeRPCClient('127.0.0.1', 58846, 'localclient', '')
>>> client.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/deluge_client/client.py", line 60, in connect
    result = self.call('daemon.login', self.username, self.password)
  File "/usr/local/lib/python2.7/dist-packages/deluge_client/client.py", line 89, in call
    raise CallTimeoutException()
deluge_client.client.CallTimeoutException
```

Deluge-web Work is normal ...
I look at the development of the current branch daemon.login part, can help me look at the problem?

**Comment by JohnDoee** [comment]
It seems like they added a requirement for client version when logging in. They also wanted to change the protocol a little and that might have come into effect now too.

If you want to do a quick test for an easy fix, try changing https://github.com/JohnDoee/deluge-client/blob/develop/deluge_client/client.py#L60 to

            result = self.call('daemon.login', self.username, self.password, client_version='deluge-client')

**Comment by kslr** [comment]
Thank you for the information that I am trying to do with plugin solution. But that's a bad idea. 
The new RPC looks like a mandatory use of SSL...

**Comment by kslr** [comment]
I tried to replace two places and tested separately, but could not work.

**Comment by JohnDoee** [comment]
I apologize for not getting around to fix this, I forgot all about it.

Anyways, deluge 2 support has been added and is release
