### ISSUE TITLE
Adding torrents

### ISSUE THREAD

**Issue by mgaulton** [JohnDoee/deluge-client#9]
Hey There, 
I'm having issues with the AutoAdd plugin and multiple folders so I'm looking to add torrents, with labels, from paths. i'm wondering how I might do that with your code? I'm not that familiar with the API.
for each in Folder1 Folder2; do 
  for each in $(ls *.torrent); do
    (add torrent with label code)

**Comment by kslr** [comment]
https://github.com/kslr/deluge/blob/develop/deluge/plugins/AutoAdd/deluge/plugins/autoadd/core.py#L282

**Comment by JohnDoee** [comment]
That's not really what this client is for.
